# Generated by Django 4.2.8 on 2023-12-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideagroup',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ideagroup',
            name='status',
            field=models.CharField(default='active', max_length=255),
        ),
    ]
