# Generated by Django 4.2.8 on 2024-01-19 21:23

from django.db import migrations, models
import django.db.models.deletion
import frontend.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideagroup',
            name='organization',
            field=models.ForeignKey(blank=True, default=frontend.models.get_default_organization, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ideagroups', to='frontend.organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
