# Generated by Django 4.2.8 on 2024-03-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profilePic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('guest', 'Guest')], default='user', max_length=20),
        ),
    ]
