# Generated by Django 4.2.8 on 2023-12-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_ideagroup_description_ideagroup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideagroup',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
