# Generated by Django 4.2.8 on 2024-01-28 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_ideagroup_organization_alter_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideagroup',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ideagroups', to='frontend.organization'),
        ),
    ]
