# Generated by Django 4.2.8 on 2024-01-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_ideagroup_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profilePic',
            field=models.ImageField(blank=True, default='profile_pics/profile_pic_anon.svg', null=True, upload_to='profile_pics/'),
        ),
    ]
