# Generated by Django 4.2.8 on 2024-03-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
