# Generated by Django 4.2.8 on 2023-12-23 07:03

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_ideagroup_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideagroup',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
