# Generated by Django 4.2.8 on 2024-02-20 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='likes',
        ),
    ]
