# Generated by Django 4.2.8 on 2024-02-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_person_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='Wildcat1411', max_length=128),
            preserve_default=False,
        ),
    ]
