# Generated by Django 4.2.8 on 2024-03-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_remove_idea_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profilePic',
            field=models.ImageField(blank=True, default='profile_pic_anon.svg', null=True, upload_to='profile_pics/'),
        ),
    ]
